function output = generateOutputMatrix(data, cols, n)

% [prctile(itemdata(:,strcmp('rt', cols)), [10 30 50 70 90]),
% ncorrect(item,1), noutliers(item,1), nerrors(item,1), mrt(item,1)]



output = [...
    aggregate(data, find(strcmp(cols, 'itm')), find(strcmp(cols, 'rt')), @(x)(prctile(x, 10))),...
    aggregate(data, find(strcmp(cols, 'itm')), find(strcmp(cols, 'rt')), @(x)(prctile(x, 30)), 1),...
    aggregate(data, find(strcmp(cols, 'itm')), find(strcmp(cols, 'rt')), @(x)(prctile(x, 50)), 1),...
    aggregate(data, find(strcmp(cols, 'itm')), find(strcmp(cols, 'rt')), @(x)(prctile(x, 70)), 1),...
    aggregate(data, find(strcmp(cols, 'itm')), find(strcmp(cols, 'rt')), @(x)(prctile(x, 90)), 1),...
    aggregate(data, find(strcmp(cols, 'itm')), find(strcmp(cols, 'acc')), @sum, 1),...
    n.outlierRTsRemovedPerItem',...
    aggregate([data(:,strcmp(cols, 'itm')), 1-data(:,strcmp(cols, 'acc'))],...
        1, 2, @sum, 1),...
    aggregate(data(data(:,strcmp(cols, 'acc')) == 1, :),...
    find(strcmp(cols, 'itm')), find(strcmp(cols, 'rt')), @mean, 1)        
];

